# Generated by Django 6.0 on 2026-02-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
        ("posts", "0002_alter_post_author_alter_post_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
