# Generated by Django 6.0 on 2026-03-01 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
