# Generated by Django 6.0 on 2026-02-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=70)),
                ("roll", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.TextField()),
            ],
        ),
    ]
