# Generated by Django 6.0 on 2026-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fathers_name",
            field=models.TextField(default="Rahim"),
        ),
    ]
