# Generated by Django 6.0 on 2026-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_student_fathers_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                ("name", models.CharField(max_length=70)),
                ("roll", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.TextField()),
                ("fathers_name", models.CharField(max_length=40)),
            ],
        ),
    ]
