# Generated by Django 6.0 on 2026-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="slug",
            field=models.SlugField(blank=True, unique=True, null=True),
        ),
    ]
