# Generated by Django 6.0 on 2026-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
